#ifndef CODEPASTER_GLOBAL_H
#define CODEPASTER_GLOBAL_H

#include <QtGlobal>

#if defined(CODEPASTER_LIBRARY)
#  define CODEPASTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CODEPASTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CODEPASTER_GLOBAL_H

